client_config_backend: settings
client_config:
    client_id: "984673059643-k8kmpo3punlqs3ihs9geu129guucmt14.apps.googleusercontent.com"
    client_secret: "Ab4IVt0ViTEVpO6VOp9u4Jmu"


save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True
